### ISSUE TITLE
Binary (architecture) incompatibility

### ISSUE THREAD

**Issue by ghost** [sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-#13]
As you know, binaries like sqlite3 , zipalign and rngd(seeder) is compiled for various archs. There are no current util binary that is universally compatible, so make sure you guys use the right binary for the right arch

**Comment by storm1er** [comment]
As you can see [here](https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/blob/master/installer/setup/install_sqlite.sh), I already made custom script & binaries for sqlite3

Feel free to pull request with your scripts for other bin :)

**Comment by ghost** [comment]
Didn't analyse the source properly. Thanks ;)
