### ISSUE TITLE
Find zipalign PIE binary

### ISSUE THREAD

**Issue by storm1er** [sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-#6]
And check if it is really usefull in android 5+

**Comment by storm1er** [comment]
Or maybe build it ?

Edit, sorry, I wanted to say or* not your*

**Comment by sohamxda7** [comment]
im finding

**Comment by sohamxda7** [comment]
check this out

https://www.datafilehost.com/d/8724dda0

**Comment by storm1er** [comment]
Did you try it/them ?

EDIT : on android 5+

**Comment by sohamxda7** [comment]
No 
but i saw those were posted after the release of.lolipop 

maybe we should give a try to the zipalign

**Comment by storm1er** [comment]
Yup, can you do that ?

- Put your phone in recovery
- `adb push ./zipalign /tmp/zipalign`
- `adb shell` your phone
- `chmod a+x /tmp/zipalign`
- `/tmp/zipalign`

No error ? Then Yay
Error ? Then f*ck, let's find another one

Tell me ;)

**Comment by storm1er** [comment]
duplicated here : https://github.com/storm1er/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/issues/3
